version: '3.7'
services:
  app:
    container_name: symfony-mt-example-app
    image: nginx:1.21-alpine
    ports:
      - "17000:80"
    volumes:
      - ./:/app:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: symfony-mt-example-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=symfony-mt-example.local
    volumes:
      - ./:/app:delegated
    networks:
      - default
      - symfony-mt-example-net

  db-client-one:
    container_name: symfony-mt-example-db-client-one
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_PASSWORD: guest
      MYSQL_USER: guest
      MYSQL_DATABASE: db_one
    ports:
      - "17001:3306"
    volumes:
      - symfony-mt-example_db_client_one:/var/lib/mysql
      - ./docker/sql/db_one.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - default
      - symfony-mt-example-net

  db-client-two:
    container_name: symfony-mt-example-db-client-two
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_PASSWORD: guest
      MYSQL_USER: guest
      MYSQL_DATABASE: db_two
    ports:
      - "17002:3306"
    volumes:
      - symfony-mt-example_db_client_two:/var/lib/mysql
      - ./docker/sql/db_two.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - default
      - symfony-mt-example-net


volumes:
  symfony-mt-example_db_client_one:
  symfony-mt-example_db_client_two:

networks:
  default:
    name: examples-net
  symfony-mt-example-net: